### ISSUE TITLE
pretrained model link not working

### ISSUE THREAD

**Issue by satyajitghana** [ZHANGKEON/DIS-YOLO#5]
Hi,

The Pretrained Model Link Provided: https://drive.google.com/drive/folders/1LDE08DwQaA79-lq7NKPU7ieb_DOh9VSk?usp=sharing is not working

**Comment by ming94good** [comment]
Hi, same question here

**Comment by ming94good** [comment]
Same question here.

**Comment by ming94good** [comment]
@ZHANGKEON sincerely look forward to your reply.

**Comment by ming94good** [comment]
@ZHANGKEON Please reply 😞

**Comment by ZHANGKEON** [comment]
The link is updated.
