### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Sanctuary345** [ZHANGKEON/DIS-YOLO#8]
Hello! Congratulations on your excellent work! I download the data, but it need password to unzip.
I have sent a email to owner already, but no response yet.
So can you share the unzip password with other ways?
Thanks!

**Comment by prince0310** [comment]
@DuHao55  Hey Have you got the key ?

**Comment by prince0310** [comment]
HI @ZHANGKEON can you please provide the password

**Comment by jamal-saeedi** [comment]
Sure, here’s a revised version:

Hello  @ZHANGKEON,

It seems that the password is missing. I’ve already sent an email but haven’t received a response yet. Could you please assist me with this?

Thank you!
